import json
from github import Github, GithubException


def _find_existing_pr(repo, title_prefix: str) -> str | None:
    for pr in repo.get_pulls(state="open"):
        if pr.title.startswith(title_prefix):
            return pr.html_url
    return None


def _build_pr_body(
    cloud: str,
    identity: str,
    findings: list[dict],
    current_policy: str,
    new_policy: str,
    days: int,
) -> str:
    total = len(findings)
    to_remove = [f for f in findings if f.get("recommendation", "").lower() == "remove"]

    rows = "\n".join(
        f"| `{f['permission']}` | {f.get('last_used', 'never')} "
        f"| {f.get('recommendation', 'investigate')} | {f.get('risk', 'unknown')} |"
        for f in findings
    )

    return f"""## IAM Permission Tightening — {identity}

**Cloud:** {cloud.upper()}
**Analysis window:** last {days} days
**Unused permissions found:** {total}
**Recommended for removal:** {len(to_remove)}

### Permission Analysis

| Permission | Last Used | Recommendation | Risk |
|------------|-----------|----------------|------|
{rows}

### Policy Diff

<details>
<summary>Current policy</summary>

```json
{current_policy}
```

</details>

<details>
<summary>Proposed minimal policy</summary>

```json
{new_policy}
```

</details>

### How to test
1. Apply the new policy in a staging environment
2. Run your normal workload for 24–48 hours
3. Check CloudWatch / Cloud Audit Logs for any `AccessDenied` errors
4. If clean, apply to production

### Generated by
[iam-zero](https://github.com/MaripeddiSupraj/iam-zero) — automated least-privilege IAM analysis
"""


def open_pr(
    github_token: str,
    repo_name: str,
    cloud: str,
    identity: str,
    identity_short: str,
    findings: list[dict],
    current_policy: str,
    new_policy: str,
    days: int,
    branch_name: str,
    base_branch: str = "main",
) -> tuple[str, bool]:
    """
    Returns (pr_url, is_new).
    is_new=True  → PR was just created.
    is_new=False → an open PR for this identity already existed.
    """
    title = f"fix(iam): tighten permissions for {identity_short} [{cloud}]"
    body = _build_pr_body(cloud, identity, findings, current_policy, new_policy, days)

    gh = Github(github_token)
    try:
        repo = gh.get_repo(repo_name)
    except GithubException as e:
        raise RuntimeError(
            f"Cannot access GitHub repo '{repo_name}' — check your token and repo name.\n"
            f"  Error: {e.data.get('message', str(e))}"
        ) from e

    existing = _find_existing_pr(repo, f"fix(iam): tighten permissions for {identity_short}")
    if existing:
        return existing, False

    try:
        pr = repo.create_pull(
            title=title,
            body=body,
            head=branch_name,
            base=base_branch,
        )
        return pr.html_url, True
    except GithubException as e:
        raise RuntimeError(
            f"Failed to open PR: {e.data.get('message', str(e))}"
        ) from e
